実装完了#6
sgnn724/lamp_practice pull request #7
Opened 2021-01-28 09:02 UTC by sgnn724

実装完了しましたので、確認お願いします。

2021-01-28 11:54 UTC, primestyleus requested changes
@sgnn724 
対応ありがとうございます。ちょっと対応内容が正しく伝わっていなかったようですが、$params=array(....)のように、配列の定義をする必要があります。動作確認していただくとわかると思いますが、今の状態だとサイトが正常に機能しなくなっていると思います。確認と修正をお願いします。

2021-01-29 13:56 UTC, sgnn724 commented
修正しました。ご確認よろしくお願いします。

2021-01-29 14:38 UTC, primestyleus requested changes
@sgnn724 
まだ修正できていません。動作確認（実際に画面から操作して正しく動くかどうかの確認）をしてみてください。

2021-01-29 14:38 UTC, primestyleus commented on www/model/cart.php
> +  return fetch_all_query($db, $sql, $params = array());
$user_idを$paramsに設定することで、正しくデータバインディングができます。
`$params = array($user_id);`
という行を追加した上で、fetch_all_queryを実行することになります。

2021-01-30 05:36 UTC, sgnn724 commented
再度修正しました。ご確認よろしくお願いいたします。

2021-01-30 06:04 UTC, merged

2021-01-30 06:04 UTC, primestyleus commented
@sgnn724 
修正お疲れさまでした。マージしましたのでDevelopのPULLをお願いします。