実装完了#8
sgnn724/lamp_practice pull request #9
Opened 2021-01-31 08:05 UTC by sgnn724

実装完了しました。ご確認お願いします。

2021-01-31 13:14 UTC, primestyleus requested changes
@sgnn724 
変更対応おつかれさまです。全体的によくでてきます！とてもおしいのですが、「is_valid_csrf_token」の使い方を見直してください。関数を呼び出すと、照合結果がtrue/falseで返却されます。falseの場合は、照合できなかったということなので、処理を止めなければなりません。具体的には、falseが返ってきた時点でログインページにリダイレクトさせることが必要です。また、現状「login_as」の後でチェックをしていますが、これだとログイン処理がすでに行われたあとなので、それよりも前にトークンチェックが必要となります。修正、よろしくお願いいたします。

2021-02-01 11:39 UTC, sgnn724 commented
詳しく説明頂きありがとうございます。修正しましたので、ご確認よろしくお願いします。

2021-02-01 12:45 UTC, primestyleus reviewed
@sgnn724 
修正ありがとうございます。ログインページの対応はこれでOKです！
同じ用に、POSTを使っている他のフォームについても引き続き対応してみてください。
よろしくお願いいたします。

2021-02-02 11:54 UTC, sgnn724 commented
その他のフォームについても対応しました。ご確認お願いします。

2021-02-02 11:58 UTC, primestyleus approved these changes

2021-02-02 11:58 UTC, merged

2021-02-02 11:58 UTC, primestyleus commented
@sgnn724 
マージしました。developのPULLをお願いします。